// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNNk0icEn_yp3arbNgx8jYjQ2Pm8Dg0c8',
    appId: '1:486278251956:web:04d006406b723bc0be1ee1',
    messagingSenderId: '486278251956',
    projectId: 'tobeto-lms-project',
    authDomain: 'tobeto-lms-project.firebaseapp.com',
    storageBucket: 'tobeto-lms-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDER2MUEd8rcU7jIGGJ7BlYUC3H0VVo4HA',
    appId: '1:486278251956:android:f98b78bc33490e1cbe1ee1',
    messagingSenderId: '486278251956',
    projectId: 'tobeto-lms-project',
    storageBucket: 'tobeto-lms-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZBfJDDLpK1fREiPyMUjHnuU7sGM1PHI',
    appId: '1:486278251956:ios:71bab70c80451e68be1ee1',
    messagingSenderId: '486278251956',
    projectId: 'tobeto-lms-project',
    storageBucket: 'tobeto-lms-project.appspot.com',
    iosBundleId: 'com.example.tobetoLmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZBfJDDLpK1fREiPyMUjHnuU7sGM1PHI',
    appId: '1:486278251956:ios:5b1e8366a3a2bb95be1ee1',
    messagingSenderId: '486278251956',
    projectId: 'tobeto-lms-project',
    storageBucket: 'tobeto-lms-project.appspot.com',
    iosBundleId: 'com.example.tobetoLmsProject.RunnerTests',
  );
}
